version: '2'
services:

  mysql:
    image: mysql:latest
    ports:
      - "33666:3306"
    volumes:
      - "/var/lib/mysql"
      - "./.docker/sql:/docker-entrypoint-initdb.d"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beneli
      MYSQL_USER: beneli
      MYSQL_PASSWORD: beneli

  apache:
    image: chialab/php:5.6-apache
    ports:
      - "50000:80"
    volumes:
      - "./build:/var/www/html/"
    restart: always
    links:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: beneli
      DB_USER: beneli
      DB_PASSWORD: beneli